### ISSUE TITLE
front page needs to filter for active projects and plans

### ISSUE THREAD

**Issue by mikelmaron** [state-hiu/osmgeoweek-2015#13]
the front page listing of projects and plans needs to follow the logic to filter for active posts

https://github.com/state-hiu/osmgeoweek-2015/blob/gh-pages/projects/index.html#L27-L36

https://github.com/state-hiu/osmgeoweek-2015/blob/gh-pages/plan/index.html#L31-L39

**Comment by d3netxer** [comment]
good catch, fixed.
