### ISSUE TITLE
Titles Left-aligned 

### ISSUE THREAD

**Issue by rhyade** [state-hiu/osmgeoweek-2015#24]
Currently the first title of almost all of the days has a portion that is left aligned. 
![example1](https://cloud.githubusercontent.com/assets/15251693/11151441/1d4304ac-89fb-11e5-86c2-f5c44cd2e282.PNG)
![example2](https://cloud.githubusercontent.com/assets/15251693/11151444/1d4652a6-89fb-11e5-8ede-17b4ed27e8d0.PNG)
![example3](https://cloud.githubusercontent.com/assets/15251693/11151445/1d467b50-89fb-11e5-840f-8a588d8c4132.PNG)
![example4](https://cloud.githubusercontent.com/assets/15251693/11151442/1d441e46-89fb-11e5-938a-26634d847500.PNG)
![example5](https://cloud.githubusercontent.com/assets/15251693/11151443/1d458e5c-89fb-11e5-9ee9-fe341ea3111b.PNG)

**Comment by d3netxer** [comment]
good catch, fixed by making the title span the whole page
