### ISSUE TITLE
bare host name returns 404

### ISSUE THREAD

**Issue by bgirardot** [state-hiu/osmgeoweek-2015#4]
http://osmgeoweek.org/ returns a 404
![2015-09-18_01h58_05](https://cloud.githubusercontent.com/assets/265831/9948987/bd2465da-5da8-11e5-85a0-f756e08d711d.png)

**Comment by d3netxer** [comment]
Ok last night I changed the osmgeoweek repo to osmgeoweek-2014 and I think that broke it, changing it back to osmgeoweek in the meantime and hopefully it will work

**Comment by d3netxer** [comment]
2014 version of the site got back up last week. Thanks for the notification. Hopefully 2015 site will launch on Monday or Tuesday.
