### ISSUE TITLE
http://www.osmgeoweek.org/ returns a dns error

### ISSUE THREAD

**Issue by bgirardot** [state-hiu/osmgeoweek-2015#5]

**Comment by d3netxer** [comment]
Ok last night I changed the osmgeoweek repo to osmgeoweek-2014 and I think that broke it, changing it back to osmgeoweek in the meantime and hopefully it will work

**Comment by bensonwilder** [comment]
Site is still down - what do we need to do? Would be useful to get it back
up as we promote this year's effort by showing people what was done last
year

**Comment by d3netxer** [comment]
2014 version of the site got back up last week. Thanks for the notification. Hopefully 2015 site will launch on Monday or Tuesday.
