### ISSUE TITLE
Fix broken link on 'Event Guide' page

### ISSUE THREAD

**Issue by geomantic** [state-hiu/osmgeoweek-2015#7]
http://osmgeoweek.org/project/nyamira/ -> 404

**Comment by d3netxer** [comment]
I guess I need to create a project page for that project then, do you know where I can find the details?

I'm seeing the project on the TM: http://tasks.hotosm.org/project/759

**Comment by geomantic** [comment]
Hm...no, not a project I'm familiar with. But if you see it on the TM, maybe just update the link?

**Comment by d3netxer** [comment]
Ok, I'll try to contact the TM project manager to see if there are any updates, then update the link.

**Comment by d3netxer** [comment]
I fixed the link so it still works: http://osmgeoweek.org/project/nyamira/

but I did not make it a featured project so it is not in the projects page

**Comment by bensonwilder** [comment]
@mikelmaron have been you been back in touch with Mr. Nyakiri since last year? Either way, want to loop him in with us?

**Comment by mikelmaron** [comment]
sure, I just sent an email connecting you
